
import { Note, ChordFormula, Difficulty, Language, FretboardPosition } from './types';

export const NOTES: Note[] = ['C', 'C#', 'D', 'D#', 'E', 'F', 'F#', 'G', 'G#', 'A', 'A#', 'B'];

export const CHORD_FORMULAS: ChordFormula[] = [
  { suffix: '', intervals: [0, 4, 7], fullName: 'Major' },
  { suffix: 'm', intervals: [0, 3, 7], fullName: 'Minor' },
  { suffix: '7', intervals: [0, 4, 7, 10], fullName: 'Dominant 7th' },
  { suffix: 'maj7', intervals: [0, 4, 7, 11], fullName: 'Major 7th' },
  { suffix: 'm7', intervals: [0, 3, 7, 10], fullName: 'Minor 7th' },
  { suffix: 'sus4', intervals: [0, 5, 7], fullName: 'Suspended 4th' },
  { suffix: 'sus2', intervals: [0, 2, 7], fullName: 'Suspended 2nd' },
  { suffix: 'dim', intervals: [0, 3, 6], fullName: 'Diminished' },
  { suffix: 'dim7', intervals: [0, 3, 6, 9], fullName: 'Diminished 7th' },
  { suffix: 'm7b5', intervals: [0, 3, 6, 10], fullName: 'Half-Diminished 7th' },
  { suffix: 'aug', intervals: [0, 4, 8], fullName: 'Augmented' },
  { suffix: '6', intervals: [0, 4, 7, 9], fullName: 'Major 6th' },
  { suffix: 'm6', intervals: [0, 3, 7, 9], fullName: 'Minor 6th' },
  { suffix: '9', intervals: [0, 4, 7, 10, 14], fullName: 'Dominant 9th' },
  { suffix: 'maj9', intervals: [0, 4, 7, 11, 14], fullName: 'Major 9th' },
  { suffix: 'm9', intervals: [0, 3, 7, 10, 14], fullName: 'Minor 9th' },
  { suffix: '13', intervals: [0, 4, 7, 10, 14, 21], fullName: 'Dominant 13th' },
  { suffix: '7#9', intervals: [0, 4, 7, 10, 15], fullName: 'Dominant 7th Sharp 9' },
  { suffix: '7b9', intervals: [0, 4, 7, 10, 13], fullName: 'Dominant 7th Flat 9' },
  { suffix: '6/9', intervals: [0, 4, 7, 9, 14], fullName: 'Major 6/9' },
  { suffix: 'add9', intervals: [0, 4, 7, 14], fullName: 'Added 9th' },
];

export const CHORD_SHAPES: Record<string, { positions: FretboardPosition[], baseFret?: number }> = {
  'C': { positions: [{ string: 5, fret: 3 }, { string: 4, fret: 2 }, { string: 2, fret: 1 }, { string: 6, fret: 'x' }] },
  'G': { positions: [{ string: 6, fret: 3 }, { string: 5, fret: 2 }, { string: 1, fret: 3 }] },
  'D': { positions: [{ string: 4, fret: 0 }, { string: 3, fret: 2 }, { string: 2, fret: 3 }, { string: 1, fret: 2 }, { string: 5, fret: 'x' }, { string: 6, fret: 'x' }] },
  'A': { positions: [{ string: 5, fret: 0 }, { string: 4, fret: 2 }, { string: 3, fret: 2 }, { string: 2, fret: 2 }, { string: 6, fret: 'x' }] },
  'E': { positions: [{ string: 6, fret: 0 }, { string: 5, fret: 2 }, { string: 4, fret: 2 }, { string: 3, fret: 1 }] },
  'Am': { positions: [{ string: 5, fret: 0 }, { string: 4, fret: 2 }, { string: 3, fret: 2 }, { string: 2, fret: 1 }, { string: 6, fret: 'x' }] },
  'Em': { positions: [{ string: 6, fret: 0 }, { string: 5, fret: 2 }, { string: 4, fret: 2 }] },
  'Dm': { positions: [{ string: 4, fret: 0 }, { string: 3, fret: 2 }, { string: 2, fret: 3 }, { string: 1, fret: 1 }, { string: 5, fret: 'x' }, { string: 6, fret: 'x' }] },
  'F': { positions: [{ string: 6, fret: 1 }, { string: 5, fret: 3 }, { string: 4, fret: 3 }, { string: 3, fret: 2 }, { string: 2, fret: 1 }, { string: 1, fret: 1 }] },
  'Bm': { positions: [{ string: 5, fret: 2 }, { string: 4, fret: 4 }, { string: 3, fret: 4 }, { string: 2, fret: 3 }, { string: 1, fret: 2 }, { string: 6, fret: 'x' }] },
  'C7': { positions: [{ string: 5, fret: 3 }, { string: 4, fret: 2 }, { string: 3, fret: 3 }, { string: 2, fret: 1 }, { string: 6, fret: 'x' }] },
  'G7': { positions: [{ string: 6, fret: 3 }, { string: 5, fret: 2 }, { string: 1, fret: 1 }] },
  'D7': { positions: [{ string: 4, fret: 0 }, { string: 3, fret: 2 }, { string: 2, fret: 1 }, { string: 1, fret: 2 }, { string: 5, fret: 'x' }, { string: 6, fret: 'x' }] },
  'A7': { positions: [{ string: 5, fret: 0 }, { string: 4, fret: 2 }, { string: 2, fret: 2 }, { string: 6, fret: 'x' }] },
  'E7': { positions: [{ string: 6, fret: 0 }, { string: 5, fret: 2 }, { string: 3, fret: 1 }] },
  'B7': { positions: [{ string: 5, fret: 2 }, { string: 4, fret: 1 }, { string: 3, fret: 2 }, { string: 1, fret: 2 }, { string: 6, fret: 'x' }] },
  'Fmaj7': { positions: [{ string: 4, fret: 3 }, { string: 3, fret: 2 }, { string: 2, fret: 1 }, { string: 1, fret: 0 }, { string: 5, fret: 'x' }, { string: 6, fret: 'x' }] },
  'Csus4': { positions: [{ string: 5, fret: 3 }, { string: 4, fret: 3 }, { string: 3, fret: 0 }, { string: 2, fret: 1 }, { string: 6, fret: 'x' }] },
  'Gsus4': { positions: [{ string: 6, fret: 3 }, { string: 5, fret: 3 }, { string: 4, fret: 0 }, { string: 3, fret: 0 }, { string: 2, fret: 1 }, { string: 1, fret: 3 }] },
  'Asus2': { positions: [{ string: 5, fret: 0 }, { string: 4, fret: 2 }, { string: 3, fret: 2 }, { string: 2, fret: 0 }, { string: 6, fret: 'x' }] },
  'Esus4': { positions: [{ string: 6, fret: 0 }, { string: 5, fret: 2 }, { string: 4, fret: 2 }, { string: 3, fret: 2 }] },
  'Csus2': { positions: [{ string: 5, fret: 3 }, { string: 4, fret: 0 }, { string: 3, fret: 0 }, { string: 2, fret: 3 }, { string: 6, fret: 'x' }] },
  'Dsus4': { positions: [{ string: 4, fret: 0 }, { string: 3, fret: 2 }, { string: 2, fret: 3 }, { string: 1, fret: 3 }, { string: 5, fret: 'x' }, { string: 6, fret: 'x' }] },
  'Asus4': { positions: [{ string: 5, fret: 0 }, { string: 4, fret: 2 }, { string: 3, fret: 2 }, { string: 2, fret: 3 }, { string: 1, fret: 0 }, { string: 6, fret: 'x' }] },
  'Dsus2': { positions: [{ string: 4, fret: 0 }, { string: 3, fret: 2 }, { string: 2, fret: 3 }, { string: 1, fret: 0 }, { string: 5, fret: 'x' }, { string: 6, fret: 'x' }] },
  'C6': { positions: [{ string: 5, fret: 3 }, { string: 4, fret: 2 }, { string: 3, fret: 2 }, { string: 2, fret: 1 }, { string: 6, fret: 'x' }] },
  'G9': { positions: [{ string: 6, fret: 3 }, { string: 5, fret: 2 }, { string: 4, fret: 3 }, { string: 3, fret: 2 }, { string: 2, fret: 3 }, { string: 1, fret: 'x' }] },
  'E7#9': { positions: [{ string: 6, fret: 0 }, { string: 5, fret: 7 }, { string: 4, fret: 6 }, { string: 3, fret: 7 }, { string: 2, fret: 8 }, { string: 1, fret: 'x' }] },
  'A13': { positions: [{ string: 6, fret: 5 }, { string: 5, fret: 'x' }, { string: 4, fret: 5 }, { string: 3, fret: 6 }, { string: 2, fret: 7 }, { string: 1, fret: 'x' }] },
  'Cmaj9': { positions: [{ string: 5, fret: 3 }, { string: 4, fret: 2 }, { string: 3, fret: 4 }, { string: 2, fret: 3 }, { string: 6, fret: 'x' }, { string: 1, fret: 'x' }] },
  'Am9': { positions: [{ string: 6, fret: 5 }, { string: 5, fret: 'x' }, { string: 4, fret: 5 }, { string: 3, fret: 5 }, { string: 2, fret: 5 }, { string: 1, fret: 7 }] },
  'G6/9': { positions: [{ string: 6, fret: 3 }, { string: 5, fret: 2 }, { string: 4, fret: 2 }, { string: 3, fret: 2 }, { string: 2, fret: 3 }, { string: 1, fret: 'x' }] },
  'D7b9': { positions: [{ string: 5, fret: 5 }, { string: 4, fret: 4 }, { string: 3, fret: 5 }, { string: 2, fret: 4 }, { string: 6, fret: 'x' }, { string: 1, fret: 'x' }] },
  'Cdim': { positions: [{ string: 5, fret: 3 }, { string: 4, fret: 4 }, { string: 3, fret: 5 }, { string: 2, fret: 4 }, { string: 6, fret: 'x' }] },
  'Caug': { positions: [{ string: 5, fret: 3 }, { string: 4, fret: 2 }, { string: 3, fret: 1 }, { string: 2, fret: 1 }, { string: 6, fret: 'x' }] },
  'C/E': { positions: [{ string: 6, fret: 0 }, { string: 5, fret: 3 }, { string: 4, fret: 2 }, { string: 3, fret: 0 }, { string: 2, fret: 1 }, { string: 1, fret: 0 }] },
  'G/B': { positions: [{ string: 5, fret: 2 }, { string: 4, fret: 0 }, { string: 3, fret: 0 }, { string: 2, fret: 3 }, { string: 1, fret: 3 }, { string: 6, fret: 'x' }] },
  'F#m': { baseFret: 2, positions: [{ string: 6, fret: 2 }, { string: 5, fret: 4 }, { string: 4, fret: 4 }, { string: 3, fret: 2 }, { string: 2, fret: 2 }, { string: 1, fret: 2 }] },
  'G#m': { baseFret: 4, positions: [{ string: 6, fret: 4 }, { string: 5, fret: 6 }, { string: 4, fret: 6 }, { string: 3, fret: 4 }, { string: 2, fret: 4 }, { string: 1, fret: 4 }] },
  'C#m': { baseFret: 4, positions: [{ string: 5, fret: 4 }, { string: 4, fret: 6 }, { string: 3, fret: 6 }, { string: 2, fret: 5 }, { string: 1, fret: 4 }, { string: 6, fret: 'x' }] },
  'Bb': { baseFret: 1, positions: [{ string: 5, fret: 1 }, { string: 4, fret: 3 }, { string: 3, fret: 3 }, { string: 2, fret: 3 }, { string: 1, fret: 1 }, { string: 6, fret: 'x' }] },
  'Eb': { baseFret: 6, positions: [{ string: 5, fret: 6 }, { string: 4, fret: 8 }, { string: 3, fret: 8 }, { string: 2, fret: 8 }, { string: 1, fret: 6 }, { string: 6, fret: 'x' }] },
  'Ab': { baseFret: 4, positions: [{ string: 6, fret: 4 }, { string: 5, fret: 6 }, { string: 4, fret: 6 }, { string: 3, fret: 5 }, { string: 2, fret: 4 }, { string: 1, fret: 4 }] },
  'Db': { baseFret: 4, positions: [{ string: 5, fret: 4 }, { string: 4, fret: 6 }, { string: 3, fret: 6 }, { string: 2, fret: 6 }, { string: 1, fret: 4 }, { string: 6, fret: 'x' }] },
  'F#': { baseFret: 2, positions: [{ string: 6, fret: 2 }, { string: 5, fret: 4 }, { string: 4, fret: 4 }, { string: 3, fret: 3 }, { string: 2, fret: 2 }, { string: 1, fret: 2 }] },
  'B': { baseFret: 2, positions: [{ string: 5, fret: 2 }, { string: 4, fret: 4 }, { string: 3, fret: 4 }, { string: 2, fret: 4 }, { string: 1, fret: 2 }, { string: 6, fret: 'x' }] },
  'Cmaj7': { positions: [{ string: 5, fret: 3 }, { string: 4, fret: 2 }, { string: 3, fret: 0 }, { string: 2, fret: 0 }, { string: 1, fret: 0 }, { string: 6, fret: 'x' }] },
  'Gmaj7': { positions: [{ string: 6, fret: 3 }, { string: 5, fret: 2 }, { string: 4, fret: 0 }, { string: 3, fret: 0 }, { string: 2, fret: 0 }, { string: 1, fret: 2 }] },
  'Dmaj7': { positions: [{ string: 4, fret: 0 }, { string: 3, fret: 2 }, { string: 2, fret: 2 }, { string: 1, fret: 2 }, { string: 5, fret: 'x' }, { string: 6, fret: 'x' }] },
  'Amaj7': { positions: [{ string: 5, fret: 0 }, { string: 4, fret: 2 }, { string: 3, fret: 1 }, { string: 2, fret: 2 }, { string: 1, fret: 0 }, { string: 6, fret: 'x' }] },
  'Emaj7': { positions: [{ string: 6, fret: 0 }, { string: 5, fret: 2 }, { string: 4, fret: 1 }, { string: 3, fret: 1 }, { string: 2, fret: 0 }, { string: 1, fret: 0 }] },
  'Am7': { positions: [{ string: 5, fret: 0 }, { string: 4, fret: 2 }, { string: 3, fret: 0 }, { string: 2, fret: 1 }, { string: 1, fret: 0 }, { string: 6, fret: 'x' }] },
  'Dm7': { positions: [{ string: 4, fret: 0 }, { string: 3, fret: 2 }, { string: 2, fret: 1 }, { string: 1, fret: 1 }, { string: 5, fret: 'x' }, { string: 6, fret: 'x' }] },
  'Em7': { positions: [{ string: 6, fret: 0 }, { string: 5, fret: 2 }, { string: 4, fret: 0 }, { string: 3, fret: 0 }, { string: 2, fret: 0 }, { string: 1, fret: 0 }] },
  'Gm7': { baseFret: 3, positions: [{ string: 6, fret: 3 }, { string: 5, fret: 5 }, { string: 4, fret: 3 }, { string: 3, fret: 3 }, { string: 2, fret: 3 }, { string: 1, fret: 3 }] },
  'Cm7': { baseFret: 3, positions: [{ string: 5, fret: 3 }, { string: 4, fret: 5 }, { string: 3, fret: 3 }, { string: 2, fret: 4 }, { string: 1, fret: 3 }, { string: 6, fret: 'x' }] },
  'Fm7': { baseFret: 1, positions: [{ string: 6, fret: 1 }, { string: 5, fret: 3 }, { string: 4, fret: 1 }, { string: 3, fret: 1 }, { string: 2, fret: 1 }, { string: 1, fret: 1 }] },
  'Bm7': { baseFret: 2, positions: [{ string: 5, fret: 2 }, { string: 4, fret: 4 }, { string: 3, fret: 2 }, { string: 2, fret: 3 }, { string: 1, fret: 2 }, { string: 6, fret: 'x' }] },
  'D#m': { baseFret: 6, positions: [{ string: 5, fret: 6 }, { string: 4, fret: 8 }, { string: 3, fret: 8 }, { string: 2, fret: 7 }, { string: 1, fret: 6 }, { string: 6, fret: 'x' }] },
  'Bbm': { baseFret: 1, positions: [{ string: 5, fret: 1 }, { string: 4, fret: 3 }, { string: 3, fret: 3 }, { string: 2, fret: 2 }, { string: 1, fret: 1 }, { string: 6, fret: 'x' }] },
  'G13': { positions: [{ string: 6, fret: 3 }, { string: 5, fret: 'x' }, { string: 4, fret: 3 }, { string: 3, fret: 4 }, { string: 2, fret: 5 }, { string: 1, fret: 'x' }] },
  'C13': { positions: [{ string: 5, fret: 3 }, { string: 4, fret: 'x' }, { string: 3, fret: 3 }, { string: 2, fret: 5 }, { string: 1, fret: 5 }, { string: 6, fret: 'x' }] },
  'G7#9': { positions: [{ string: 6, fret: 3 }, { string: 5, fret: 2 }, { string: 4, fret: 3 }, { string: 3, fret: 3 }, { string: 2, fret: 'x' }, { string: 1, fret: 'x' }] },
  'A7#9': { positions: [{ string: 5, fret: 0 }, { string: 4, fret: 2 }, { string: 3, fret: 0 }, { string: 2, fret: 1 }, { string: 1, fret: 'x' }, { string: 6, fret: 'x' }] },
  'Dmaj9': { positions: [{ string: 5, fret: 5 }, { string: 4, fret: 4 }, { string: 3, fret: 6 }, { string: 2, fret: 5 }, { string: 1, fret: 'x' }, { string: 6, fret: 'x' }] },
  'Gmaj9': { positions: [{ string: 6, fret: 3 }, { string: 5, fret: 'x' }, { string: 4, fret: 4 }, { string: 3, fret: 4 }, { string: 2, fret: 3 }, { string: 1, fret: 'x' }] },
  'Dm9': { positions: [{ string: 5, fret: 5 }, { string: 4, fret: 3 }, { string: 3, fret: 5 }, { string: 2, fret: 5 }, { string: 1, fret: 'x' }, { string: 6, fret: 'x' }] },
  'Em9': { positions: [{ string: 6, fret: 0 }, { string: 5, fret: 2 }, { string: 4, fret: 0 }, { string: 3, fret: 0 }, { string: 2, fret: 0 }, { string: 1, fret: 2 }] },
  'Adim7': { positions: [{ string: 4, fret: 1 }, { string: 3, fret: 2 }, { string: 2, fret: 1 }, { string: 1, fret: 2 }, { string: 5, fret: 0 }, { string: 6, fret: 'x' }] },
  'Bm7b5': { positions: [{ string: 5, fret: 2 }, { string: 4, fret: 3 }, { string: 3, fret: 2 }, { string: 2, fret: 3 }, { string: 6, fret: 'x' }, { string: 1, fret: 'x' }] },
};

export const COMMON_CHORDS: { name: string; difficulty: Difficulty }[] = [
  // Beginner
  { name: 'C', difficulty: Difficulty.Beginner },
  { name: 'G', difficulty: Difficulty.Beginner },
  { name: 'D', difficulty: Difficulty.Beginner },
  { name: 'A', difficulty: Difficulty.Beginner },
  { name: 'E', difficulty: Difficulty.Beginner },
  { name: 'Am', difficulty: Difficulty.Beginner },
  { name: 'Em', difficulty: Difficulty.Beginner },
  { name: 'Dm', difficulty: Difficulty.Beginner },
  // Intermediate
  { name: 'F', difficulty: Difficulty.Intermediate },
  { name: 'Bm', difficulty: Difficulty.Intermediate },
  { name: 'C7', difficulty: Difficulty.Intermediate },
  { name: 'G7', difficulty: Difficulty.Intermediate },
  { name: 'D7', difficulty: Difficulty.Intermediate },
  { name: 'A7', difficulty: Difficulty.Intermediate },
  { name: 'E7', difficulty: Difficulty.Intermediate },
  { name: 'B7', difficulty: Difficulty.Intermediate },
  { name: 'Fmaj7', difficulty: Difficulty.Intermediate },
  { name: 'Csus4', difficulty: Difficulty.Intermediate },
  { name: 'Gsus4', difficulty: Difficulty.Intermediate },
  { name: 'Asus2', difficulty: Difficulty.Intermediate },
  { name: 'Esus4', difficulty: Difficulty.Intermediate },
  { name: 'Csus2', difficulty: Difficulty.Intermediate },
  { name: 'C/E', difficulty: Difficulty.Intermediate },
  { name: 'G/B', difficulty: Difficulty.Intermediate },
  { name: 'Dsus4', difficulty: Difficulty.Intermediate },
  { name: 'Asus4', difficulty: Difficulty.Intermediate },
  { name: 'Dsus2', difficulty: Difficulty.Intermediate },
  { name: 'Cmaj7', difficulty: Difficulty.Intermediate },
  { name: 'Gmaj7', difficulty: Difficulty.Intermediate },
  { name: 'Dmaj7', difficulty: Difficulty.Intermediate },
  { name: 'Amaj7', difficulty: Difficulty.Intermediate },
  { name: 'Emaj7', difficulty: Difficulty.Intermediate },
  { name: 'Am7', difficulty: Difficulty.Intermediate },
  { name: 'Dm7', difficulty: Difficulty.Intermediate },
  { name: 'Em7', difficulty: Difficulty.Intermediate },
  { name: 'C6', difficulty: Difficulty.Intermediate },
  { name: 'G9', difficulty: Difficulty.Intermediate },
  // Advanced
  { name: 'F#m', difficulty: Difficulty.Advanced },
  { name: 'C#m', difficulty: Difficulty.Advanced },
  { name: 'G#m', difficulty: Difficulty.Advanced },
  { name: 'F#', difficulty: Difficulty.Advanced },
  { name: 'B', difficulty: Difficulty.Advanced },
  { name: 'Gm7', difficulty: Difficulty.Advanced },
  { name: 'Cm7', difficulty: Difficulty.Advanced },
  { name: 'Fm7', difficulty: Difficulty.Advanced },
  { name: 'Bm7', difficulty: Difficulty.Advanced },
  { name: 'D#m', difficulty: Difficulty.Advanced },
  { name: 'Bbm', difficulty: Difficulty.Advanced },
  { name: 'Cdim', difficulty: Difficulty.Advanced },
  { name: 'Adim7', difficulty: Difficulty.Advanced },
  { name: 'Bm7b5', difficulty: Difficulty.Advanced },
  { name: 'Caug', difficulty: Difficulty.Advanced },
  { name: 'Bb', difficulty: Difficulty.Advanced },
  { name: 'Eb', difficulty: Difficulty.Advanced },
  { name: 'Ab', difficulty: Difficulty.Advanced },
  { name: 'Db', difficulty: Difficulty.Advanced },
  // Jazz & Blues
  { name: 'E7#9', difficulty: Difficulty.JazzBlues },
  { name: 'A13', difficulty: Difficulty.JazzBlues },
  { name: 'Cmaj9', difficulty: Difficulty.JazzBlues },
  { name: 'Am9', difficulty: Difficulty.JazzBlues },
  { name: 'G6/9', difficulty: Difficulty.JazzBlues },
  { name: 'D7b9', difficulty: Difficulty.JazzBlues },
  { name: 'Bm7b5', difficulty: Difficulty.JazzBlues },
  { name: 'G13', difficulty: Difficulty.JazzBlues },
  { name: 'C13', difficulty: Difficulty.JazzBlues },
  { name: 'G7#9', difficulty: Difficulty.JazzBlues },
  { name: 'A7#9', difficulty: Difficulty.JazzBlues },
  { name: 'Dmaj9', difficulty: Difficulty.JazzBlues },
  { name: 'Gmaj9', difficulty: Difficulty.JazzBlues },
  { name: 'Dm9', difficulty: Difficulty.JazzBlues },
  { name: 'Em9', difficulty: Difficulty.JazzBlues },
];

export const TRANSLATIONS: Record<Language, any> = {
  'en': {
    title: 'Guitar Chord Master',
    subtitle: 'Chord Analysis & Progression Engine',
    reset: 'RESET',
    noteComposition: 'Note Composition',
    identifiedChords: 'Identified Chords',
    chordLibrary: 'Chord Library',
    suggestedProgressions: 'Suggested Progressions',
    selectNotes: 'Select notes to identify chords...',
    flowFrom: 'Chords that flow naturally from',
    selectChordHint: 'Select a chord to see smart progression suggestions',
    status: 'Status',
    ready: 'Ready',
    analyzing: 'Analyzing',
    notes: 'Notes',
    none: 'None',
    difficulty: {
      Beginner: 'Beginner',
      Intermediate: 'Intermediate',
      Advanced: 'Advanced',
      JazzBlues: 'Jazz & Blues'
    },
    chordDiagram: 'Chord Diagram',
    bassNote: 'Bass Note',
    bassHint: 'Click a selected note again to set as Bass'
  },
  'zh-TW': {
    title: '吉他和弦大師',
    subtitle: '和弦分析與進程引擎',
    reset: '重置',
    noteComposition: '音符組成',
    identifiedChords: '識別出的和弦',
    chordLibrary: '和弦庫',
    suggestedProgressions: '建議的和弦進程',
    selectNotes: '選擇音符來識別和弦...',
    flowFrom: '接在',
    selectChordHint: '選擇一個和弦來查看智能進程建議',
    status: '狀態',
    ready: '就緒',
    analyzing: '分析中',
    notes: '音符',
    none: '無',
    difficulty: {
      Beginner: '初級',
      Intermediate: '中級',
      Advanced: '高級',
      JazzBlues: '爵士與藍調'
    },
    chordDiagram: '和弦圖',
    bassNote: '低音/轉位',
    bassHint: '再次點擊已選音符可設為低音 (轉位)'
  }
};
